"""Auto-generated API-explorer catalog. DO NOT EDIT BY HAND.

Regenerate with ``python scripts/gen_catalog.py``.
Source: GitHub OpenAPI (github/rest-api-description), info.version 1.1.4.
Generated: 2026-06-23. Each row is (method, path, summary, category).
"""

from __future__ import annotations

ENDPOINTS: list[tuple[str, str, str, str]] = [
    ('GET', '/enterprises/{enterprise}/actions/cache/retention-limit', 'Get GitHub Actions cache retention limit for an enterprise', 'actions'),
    ('PUT', '/enterprises/{enterprise}/actions/cache/retention-limit', 'Set GitHub Actions cache retention limit for an enterprise', 'actions'),
    ('GET', '/enterprises/{enterprise}/actions/cache/storage-limit', 'Get GitHub Actions cache storage limit for an enterprise', 'actions'),
    ('PUT', '/enterprises/{enterprise}/actions/cache/storage-limit', 'Set GitHub Actions cache storage limit for an enterprise', 'actions'),
    ('GET', '/enterprises/{enterprise}/actions/oidc/customization/properties/repo', 'List OIDC custom property inclusions for an enterprise', 'actions'),
    ('POST', '/enterprises/{enterprise}/actions/oidc/customization/properties/repo', 'Create an OIDC custom property inclusion for an enterprise', 'actions'),
    ('DELETE', '/enterprises/{enterprise}/actions/oidc/customization/properties/repo/{custom_property_name}', 'Delete an OIDC custom property inclusion for an enterprise', 'actions'),
    ('GET', '/enterprises/{enterprise}/code-security/configurations', 'Get code security configurations for an enterprise', 'code-security'),
    ('POST', '/enterprises/{enterprise}/code-security/configurations', 'Create a code security configuration for an enterprise', 'code-security'),
    ('GET', '/enterprises/{enterprise}/code-security/configurations/defaults', 'Get default code security configurations for an enterprise', 'code-security'),
    ('GET', '/enterprises/{enterprise}/code-security/configurations/{configuration_id}', 'Retrieve a code security configuration of an enterprise', 'code-security'),
    ('PATCH', '/enterprises/{enterprise}/code-security/configurations/{configuration_id}', 'Update a custom code security configuration for an enterprise', 'code-security'),
    ('DELETE', '/enterprises/{enterprise}/code-security/configurations/{configuration_id}', 'Delete a code security configuration for an enterprise', 'code-security'),
    ('POST', '/enterprises/{enterprise}/code-security/configurations/{configuration_id}/attach', 'Attach an enterprise configuration to repositories', 'code-security'),
    ('PUT', '/enterprises/{enterprise}/code-security/configurations/{configuration_id}/defaults', 'Set a code security configuration as a default for an enterprise', 'code-security'),
    ('GET', '/enterprises/{enterprise}/code-security/configurations/{configuration_id}/repositories', 'Get repositories associated with an enterprise code security configuration', 'code-security'),
    ('GET', '/enterprises/{enterprise}/copilot/metrics/reports/enterprise-1-day', 'Get Copilot enterprise usage metrics for a specific day', 'copilot'),
    ('GET', '/enterprises/{enterprise}/copilot/metrics/reports/enterprise-28-day/latest', 'Get Copilot enterprise usage metrics', 'copilot'),
    ('GET', '/enterprises/{enterprise}/copilot/metrics/reports/user-teams-1-day', 'Get Copilot enterprise user-teams report for a specific day', 'copilot'),
    ('GET', '/enterprises/{enterprise}/copilot/metrics/reports/users-1-day', 'Get Copilot users usage metrics for a specific day', 'copilot'),
    ('GET', '/enterprises/{enterprise}/copilot/metrics/reports/users-28-day/latest', 'Get Copilot users usage metrics', 'copilot'),
    ('PUT', '/enterprises/{enterprise}/copilot/policies/coding_agent', 'Set the coding agent policy for an enterprise', 'copilot'),
    ('POST', '/enterprises/{enterprise}/copilot/policies/coding_agent/organizations', 'Add organizations to the enterprise coding agent policy', 'copilot'),
    ('DELETE', '/enterprises/{enterprise}/copilot/policies/coding_agent/organizations', 'Remove organizations from the enterprise coding agent policy', 'copilot'),
    ('GET', '/enterprises/{enterprise}/dependabot/alerts', 'List Dependabot alerts for an enterprise', 'dependabot'),
    ('GET', '/enterprises/{enterprise}/dependabot/repository-access', 'Lists the repositories Dependabot can access in an enterprise', 'dependabot'),
    ('PATCH', '/enterprises/{enterprise}/dependabot/repository-access', "Updates Dependabot's repository access list for an enterprise", 'dependabot'),
    ('PUT', '/enterprises/{enterprise}/dependabot/repository-access/default-level', 'Set the default repository access level for Dependabot in an enterprise', 'dependabot'),
    ('GET', '/enterprises/{enterprise}/teams', 'List enterprise teams', 'enterprise-teams'),
    ('POST', '/enterprises/{enterprise}/teams', 'Create an enterprise team', 'enterprise-teams'),
    ('GET', '/enterprises/{enterprise}/teams/{enterprise-team}/memberships', 'List members in an enterprise team', 'enterprise-teams'),
    ('POST', '/enterprises/{enterprise}/teams/{enterprise-team}/memberships/add', 'Bulk add team members', 'enterprise-teams'),
    ('POST', '/enterprises/{enterprise}/teams/{enterprise-team}/memberships/remove', 'Bulk remove team members', 'enterprise-teams'),
    ('GET', '/enterprises/{enterprise}/teams/{enterprise-team}/memberships/{username}', 'Get enterprise team membership', 'enterprise-teams'),
    ('PUT', '/enterprises/{enterprise}/teams/{enterprise-team}/memberships/{username}', 'Add team member', 'enterprise-teams'),
    ('DELETE', '/enterprises/{enterprise}/teams/{enterprise-team}/memberships/{username}', 'Remove team membership', 'enterprise-teams'),
    ('GET', '/enterprises/{enterprise}/teams/{enterprise-team}/organizations', 'Get organization assignments', 'enterprise-teams'),
    ('POST', '/enterprises/{enterprise}/teams/{enterprise-team}/organizations/add', 'Add organization assignments', 'enterprise-teams'),
    ('POST', '/enterprises/{enterprise}/teams/{enterprise-team}/organizations/remove', 'Remove organization assignments', 'enterprise-teams'),
    ('GET', '/enterprises/{enterprise}/teams/{enterprise-team}/organizations/{org}', 'Get organization assignment', 'enterprise-teams'),
    ('PUT', '/enterprises/{enterprise}/teams/{enterprise-team}/organizations/{org}', 'Add an organization assignment', 'enterprise-teams'),
    ('DELETE', '/enterprises/{enterprise}/teams/{enterprise-team}/organizations/{org}', 'Delete an organization assignment', 'enterprise-teams'),
    ('GET', '/enterprises/{enterprise}/teams/{team_slug}', 'Get an enterprise team', 'enterprise-teams'),
    ('PATCH', '/enterprises/{enterprise}/teams/{team_slug}', 'Update an enterprise team', 'enterprise-teams'),
    ('DELETE', '/enterprises/{enterprise}/teams/{team_slug}', 'Delete an enterprise team', 'enterprise-teams'),
    ('GET', '/meta', 'Get GitHub meta information', 'meta'),
    ('GET', '/orgs/{org}', 'Get an organization', 'orgs'),
    ('PATCH', '/orgs/{org}', 'Update an organization', 'orgs'),
    ('DELETE', '/orgs/{org}', 'Delete an organization', 'orgs'),
    ('GET', '/orgs/{org}/actions/cache/usage', 'Get GitHub Actions cache usage for an organization', 'actions'),
    ('GET', '/orgs/{org}/actions/cache/usage-by-repository', 'List repositories with GitHub Actions cache usage for an organization', 'actions'),
    ('GET', '/orgs/{org}/actions/hosted-runners', 'List GitHub-hosted runners for an organization', 'actions'),
    ('POST', '/orgs/{org}/actions/hosted-runners', 'Create a GitHub-hosted runner for an organization', 'actions'),
    ('GET', '/orgs/{org}/actions/hosted-runners/images/custom', 'List custom images for an organization', 'actions'),
    ('GET', '/orgs/{org}/actions/hosted-runners/images/custom/{image_definition_id}', 'Get a custom image definition for GitHub Actions Hosted Runners', 'actions'),
    ('DELETE', '/orgs/{org}/actions/hosted-runners/images/custom/{image_definition_id}', 'Delete a custom image from the organization', 'actions'),
    ('GET', '/orgs/{org}/actions/hosted-runners/images/custom/{image_definition_id}/versions', 'List image versions of a custom image for an organization', 'actions'),
    ('GET', '/orgs/{org}/actions/hosted-runners/images/custom/{image_definition_id}/versions/{version}', 'Get an image version of a custom image for GitHub Actions Hosted Runners', 'actions'),
    ('DELETE', '/orgs/{org}/actions/hosted-runners/images/custom/{image_definition_id}/versions/{version}', 'Delete an image version of custom image from the organization', 'actions'),
    ('GET', '/orgs/{org}/actions/hosted-runners/images/github-owned', 'Get GitHub-owned images for GitHub-hosted runners in an organization', 'actions'),
    ('GET', '/orgs/{org}/actions/hosted-runners/images/partner', 'Get partner images for GitHub-hosted runners in an organization', 'actions'),
    ('GET', '/orgs/{org}/actions/hosted-runners/limits', 'Get limits on GitHub-hosted runners for an organization', 'actions'),
    ('GET', '/orgs/{org}/actions/hosted-runners/machine-sizes', 'Get GitHub-hosted runners machine specs for an organization', 'actions'),
    ('GET', '/orgs/{org}/actions/hosted-runners/platforms', 'Get platforms for GitHub-hosted runners in an organization', 'actions'),
    ('GET', '/orgs/{org}/actions/hosted-runners/{hosted_runner_id}', 'Get a GitHub-hosted runner for an organization', 'actions'),
    ('PATCH', '/orgs/{org}/actions/hosted-runners/{hosted_runner_id}', 'Update a GitHub-hosted runner for an organization', 'actions'),
    ('DELETE', '/orgs/{org}/actions/hosted-runners/{hosted_runner_id}', 'Delete a GitHub-hosted runner for an organization', 'actions'),
    ('GET', '/orgs/{org}/actions/oidc/customization/properties/repo', 'List OIDC custom property inclusions for an organization', 'actions'),
    ('POST', '/orgs/{org}/actions/oidc/customization/properties/repo', 'Create an OIDC custom property inclusion for an organization', 'actions'),
    ('DELETE', '/orgs/{org}/actions/oidc/customization/properties/repo/{custom_property_name}', 'Delete an OIDC custom property inclusion for an organization', 'actions'),
    ('GET', '/orgs/{org}/actions/oidc/customization/sub', 'Get the customization template for an OIDC subject claim for an organization', 'actions'),
    ('PUT', '/orgs/{org}/actions/oidc/customization/sub', 'Set the customization template for an OIDC subject claim for an organization', 'actions'),
    ('GET', '/orgs/{org}/actions/permissions', 'Get GitHub Actions permissions for an organization', 'actions'),
    ('PUT', '/orgs/{org}/actions/permissions', 'Set GitHub Actions permissions for an organization', 'actions'),
    ('GET', '/orgs/{org}/actions/permissions/artifact-and-log-retention', 'Get artifact and log retention settings for an organization', 'actions'),
    ('PUT', '/orgs/{org}/actions/permissions/artifact-and-log-retention', 'Set artifact and log retention settings for an organization', 'actions'),
    ('GET', '/orgs/{org}/actions/permissions/fork-pr-contributor-approval', 'Get fork PR contributor approval permissions for an organization', 'actions'),
    ('PUT', '/orgs/{org}/actions/permissions/fork-pr-contributor-approval', 'Set fork PR contributor approval permissions for an organization', 'actions'),
    ('GET', '/orgs/{org}/actions/permissions/fork-pr-workflows-private-repos', 'Get private repo fork PR workflow settings for an organization', 'actions'),
    ('PUT', '/orgs/{org}/actions/permissions/fork-pr-workflows-private-repos', 'Set private repo fork PR workflow settings for an organization', 'actions'),
    ('GET', '/orgs/{org}/actions/permissions/repositories', 'List selected repositories enabled for GitHub Actions in an organization', 'actions'),
    ('PUT', '/orgs/{org}/actions/permissions/repositories', 'Set selected repositories enabled for GitHub Actions in an organization', 'actions'),
    ('PUT', '/orgs/{org}/actions/permissions/repositories/{repository_id}', 'Enable a selected repository for GitHub Actions in an organization', 'actions'),
    ('DELETE', '/orgs/{org}/actions/permissions/repositories/{repository_id}', 'Disable a selected repository for GitHub Actions in an organization', 'actions'),
    ('GET', '/orgs/{org}/actions/permissions/selected-actions', 'Get allowed actions and reusable workflows for an organization', 'actions'),
    ('PUT', '/orgs/{org}/actions/permissions/selected-actions', 'Set allowed actions and reusable workflows for an organization', 'actions'),
    ('GET', '/orgs/{org}/actions/permissions/self-hosted-runners', 'Get self-hosted runners settings for an organization', 'actions'),
    ('PUT', '/orgs/{org}/actions/permissions/self-hosted-runners', 'Set self-hosted runners settings for an organization', 'actions'),
    ('GET', '/orgs/{org}/actions/permissions/self-hosted-runners/repositories', 'List repositories allowed to use self-hosted runners in an organization', 'actions'),
    ('PUT', '/orgs/{org}/actions/permissions/self-hosted-runners/repositories', 'Set repositories allowed to use self-hosted runners in an organization', 'actions'),
    ('PUT', '/orgs/{org}/actions/permissions/self-hosted-runners/repositories/{repository_id}', 'Add a repository to the list of repositories allowed to use self-hosted runners in an organization', 'actions'),
    ('DELETE', '/orgs/{org}/actions/permissions/self-hosted-runners/repositories/{repository_id}', 'Remove a repository from the list of repositories allowed to use self-hosted runners in an organization', 'actions'),
    ('GET', '/orgs/{org}/actions/permissions/workflow', 'Get default workflow permissions for an organization', 'actions'),
    ('PUT', '/orgs/{org}/actions/permissions/workflow', 'Set default workflow permissions for an organization', 'actions'),
    ('GET', '/orgs/{org}/actions/runner-groups', 'List self-hosted runner groups for an organization', 'actions'),
    ('POST', '/orgs/{org}/actions/runner-groups', 'Create a self-hosted runner group for an organization', 'actions'),
    ('GET', '/orgs/{org}/actions/runner-groups/{runner_group_id}', 'Get a self-hosted runner group for an organization', 'actions'),
    ('PATCH', '/orgs/{org}/actions/runner-groups/{runner_group_id}', 'Update a self-hosted runner group for an organization', 'actions'),
    ('DELETE', '/orgs/{org}/actions/runner-groups/{runner_group_id}', 'Delete a self-hosted runner group from an organization', 'actions'),
    ('GET', '/orgs/{org}/actions/runner-groups/{runner_group_id}/hosted-runners', 'List GitHub-hosted runners in a group for an organization', 'actions'),
    ('GET', '/orgs/{org}/actions/runner-groups/{runner_group_id}/repositories', 'List repository access to a self-hosted runner group in an organization', 'actions'),
    ('PUT', '/orgs/{org}/actions/runner-groups/{runner_group_id}/repositories', 'Set repository access for a self-hosted runner group in an organization', 'actions'),
    ('PUT', '/orgs/{org}/actions/runner-groups/{runner_group_id}/repositories/{repository_id}', 'Add repository access to a self-hosted runner group in an organization', 'actions'),
    ('DELETE', '/orgs/{org}/actions/runner-groups/{runner_group_id}/repositories/{repository_id}', 'Remove repository access to a self-hosted runner group in an organization', 'actions'),
    ('GET', '/orgs/{org}/actions/runner-groups/{runner_group_id}/runners', 'List self-hosted runners in a group for an organization', 'actions'),
    ('PUT', '/orgs/{org}/actions/runner-groups/{runner_group_id}/runners', 'Set self-hosted runners in a group for an organization', 'actions'),
    ('PUT', '/orgs/{org}/actions/runner-groups/{runner_group_id}/runners/{runner_id}', 'Add a self-hosted runner to a group for an organization', 'actions'),
    ('DELETE', '/orgs/{org}/actions/runner-groups/{runner_group_id}/runners/{runner_id}', 'Remove a self-hosted runner from a group for an organization', 'actions'),
    ('GET', '/orgs/{org}/actions/runners', 'List self-hosted runners for an organization', 'actions'),
    ('GET', '/orgs/{org}/actions/runners/downloads', 'List runner applications for an organization', 'actions'),
    ('POST', '/orgs/{org}/actions/runners/generate-jitconfig', 'Create configuration for a just-in-time runner for an organization', 'actions'),
    ('POST', '/orgs/{org}/actions/runners/registration-token', 'Create a registration token for an organization', 'actions'),
    ('POST', '/orgs/{org}/actions/runners/remove-token', 'Create a remove token for an organization', 'actions'),
    ('GET', '/orgs/{org}/actions/runners/{runner_id}', 'Get a self-hosted runner for an organization', 'actions'),
    ('DELETE', '/orgs/{org}/actions/runners/{runner_id}', 'Delete a self-hosted runner from an organization', 'actions'),
    ('GET', '/orgs/{org}/actions/runners/{runner_id}/labels', 'List labels for a self-hosted runner for an organization', 'actions'),
    ('POST', '/orgs/{org}/actions/runners/{runner_id}/labels', 'Add custom labels to a self-hosted runner for an organization', 'actions'),
    ('PUT', '/orgs/{org}/actions/runners/{runner_id}/labels', 'Set custom labels for a self-hosted runner for an organization', 'actions'),
    ('DELETE', '/orgs/{org}/actions/runners/{runner_id}/labels', 'Remove all custom labels from a self-hosted runner for an organization', 'actions'),
    ('DELETE', '/orgs/{org}/actions/runners/{runner_id}/labels/{name}', 'Remove a custom label from a self-hosted runner for an organization', 'actions'),
    ('GET', '/orgs/{org}/actions/secrets', 'List organization secrets', 'actions'),
    ('GET', '/orgs/{org}/actions/secrets/public-key', 'Get an organization public key', 'actions'),
    ('GET', '/orgs/{org}/actions/secrets/{secret_name}', 'Get an organization secret', 'actions'),
    ('PUT', '/orgs/{org}/actions/secrets/{secret_name}', 'Create or update an organization secret', 'actions'),
    ('DELETE', '/orgs/{org}/actions/secrets/{secret_name}', 'Delete an organization secret', 'actions'),
    ('GET', '/orgs/{org}/actions/secrets/{secret_name}/repositories', 'List selected repositories for an organization secret', 'actions'),
    ('PUT', '/orgs/{org}/actions/secrets/{secret_name}/repositories', 'Set selected repositories for an organization secret', 'actions'),
    ('PUT', '/orgs/{org}/actions/secrets/{secret_name}/repositories/{repository_id}', 'Add selected repository to an organization secret', 'actions'),
    ('DELETE', '/orgs/{org}/actions/secrets/{secret_name}/repositories/{repository_id}', 'Remove selected repository from an organization secret', 'actions'),
    ('GET', '/orgs/{org}/actions/variables', 'List organization variables', 'actions'),
    ('POST', '/orgs/{org}/actions/variables', 'Create an organization variable', 'actions'),
    ('GET', '/orgs/{org}/actions/variables/{name}', 'Get an organization variable', 'actions'),
    ('PATCH', '/orgs/{org}/actions/variables/{name}', 'Update an organization variable', 'actions'),
    ('DELETE', '/orgs/{org}/actions/variables/{name}', 'Delete an organization variable', 'actions'),
    ('GET', '/orgs/{org}/actions/variables/{name}/repositories', 'List selected repositories for an organization variable', 'actions'),
    ('PUT', '/orgs/{org}/actions/variables/{name}/repositories', 'Set selected repositories for an organization variable', 'actions'),
    ('PUT', '/orgs/{org}/actions/variables/{name}/repositories/{repository_id}', 'Add selected repository to an organization variable', 'actions'),
    ('DELETE', '/orgs/{org}/actions/variables/{name}/repositories/{repository_id}', 'Remove selected repository from an organization variable', 'actions'),
    ('GET', '/orgs/{org}/agents/secrets', 'List organization secrets', 'agents'),
    ('GET', '/orgs/{org}/agents/secrets/public-key', 'Get an organization public key', 'agents'),
    ('GET', '/orgs/{org}/agents/secrets/{secret_name}', 'Get an organization secret', 'agents'),
    ('PUT', '/orgs/{org}/agents/secrets/{secret_name}', 'Create or update an organization secret', 'agents'),
    ('DELETE', '/orgs/{org}/agents/secrets/{secret_name}', 'Delete an organization secret', 'agents'),
    ('GET', '/orgs/{org}/agents/secrets/{secret_name}/repositories', 'List selected repositories for an organization secret', 'agents'),
    ('PUT', '/orgs/{org}/agents/secrets/{secret_name}/repositories', 'Set selected repositories for an organization secret', 'agents'),
    ('PUT', '/orgs/{org}/agents/secrets/{secret_name}/repositories/{repository_id}', 'Add selected repository to an organization secret', 'agents'),
    ('DELETE', '/orgs/{org}/agents/secrets/{secret_name}/repositories/{repository_id}', 'Remove selected repository from an organization secret', 'agents'),
    ('GET', '/orgs/{org}/agents/variables', 'List organization variables', 'agents'),
    ('POST', '/orgs/{org}/agents/variables', 'Create an organization variable', 'agents'),
    ('GET', '/orgs/{org}/agents/variables/{name}', 'Get an organization variable', 'agents'),
    ('PATCH', '/orgs/{org}/agents/variables/{name}', 'Update an organization variable', 'agents'),
    ('DELETE', '/orgs/{org}/agents/variables/{name}', 'Delete an organization variable', 'agents'),
    ('GET', '/orgs/{org}/agents/variables/{name}/repositories', 'List selected repositories for an organization variable', 'agents'),
    ('PUT', '/orgs/{org}/agents/variables/{name}/repositories', 'Set selected repositories for an organization variable', 'agents'),
    ('PUT', '/orgs/{org}/agents/variables/{name}/repositories/{repository_id}', 'Add selected repository to an organization variable', 'agents'),
    ('DELETE', '/orgs/{org}/agents/variables/{name}/repositories/{repository_id}', 'Remove selected repository from an organization variable', 'agents'),
    ('POST', '/orgs/{org}/artifacts/metadata/deployment-record', 'Create an artifact deployment record', 'orgs'),
    ('POST', '/orgs/{org}/artifacts/metadata/deployment-record/cluster/{cluster}', 'Set cluster deployment records', 'orgs'),
    ('POST', '/orgs/{org}/artifacts/metadata/storage-record', 'Create artifact metadata storage record', 'orgs'),
    ('GET', '/orgs/{org}/artifacts/{subject_digest}/metadata/deployment-records', 'List artifact deployment records', 'orgs'),
    ('GET', '/orgs/{org}/artifacts/{subject_digest}/metadata/storage-records', 'List artifact storage records', 'orgs'),
    ('POST', '/orgs/{org}/attestations/bulk-list', 'List attestations by bulk subject digests', 'orgs'),
    ('POST', '/orgs/{org}/attestations/delete-request', 'Delete attestations in bulk', 'orgs'),
    ('DELETE', '/orgs/{org}/attestations/digest/{subject_digest}', 'Delete attestations by subject digest', 'orgs'),
    ('GET', '/orgs/{org}/attestations/repositories', 'List attestation repositories', 'orgs'),
    ('DELETE', '/orgs/{org}/attestations/{attestation_id}', 'Delete attestations by ID', 'orgs'),
    ('GET', '/orgs/{org}/attestations/{subject_digest}', 'List attestations', 'orgs'),
    ('GET', '/orgs/{org}/blocks', 'List users blocked by an organization', 'orgs'),
    ('GET', '/orgs/{org}/blocks/{username}', 'Check if a user is blocked by an organization', 'orgs'),
    ('PUT', '/orgs/{org}/blocks/{username}', 'Block a user from an organization', 'orgs'),
    ('DELETE', '/orgs/{org}/blocks/{username}', 'Unblock a user from an organization', 'orgs'),
    ('GET', '/orgs/{org}/campaigns', 'List campaigns for an organization', 'campaigns'),
    ('POST', '/orgs/{org}/campaigns', 'Create a campaign for an organization', 'campaigns'),
    ('GET', '/orgs/{org}/campaigns/{campaign_number}', 'Get a campaign for an organization', 'campaigns'),
    ('PATCH', '/orgs/{org}/campaigns/{campaign_number}', 'Update a campaign', 'campaigns'),
    ('DELETE', '/orgs/{org}/campaigns/{campaign_number}', 'Delete a campaign for an organization', 'campaigns'),
    ('GET', '/orgs/{org}/code-scanning/alerts', 'List code scanning alerts for an organization', 'code-scanning'),
    ('GET', '/orgs/{org}/code-security/configurations', 'Get code security configurations for an organization', 'code-security'),
    ('POST', '/orgs/{org}/code-security/configurations', 'Create a code security configuration', 'code-security'),
    ('GET', '/orgs/{org}/code-security/configurations/defaults', 'Get default code security configurations', 'code-security'),
    ('DELETE', '/orgs/{org}/code-security/configurations/detach', 'Detach configurations from repositories', 'code-security'),
    ('GET', '/orgs/{org}/code-security/configurations/{configuration_id}', 'Get a code security configuration', 'code-security'),
    ('PATCH', '/orgs/{org}/code-security/configurations/{configuration_id}', 'Update a code security configuration', 'code-security'),
    ('DELETE', '/orgs/{org}/code-security/configurations/{configuration_id}', 'Delete a code security configuration', 'code-security'),
    ('POST', '/orgs/{org}/code-security/configurations/{configuration_id}/attach', 'Attach a configuration to repositories', 'code-security'),
    ('PUT', '/orgs/{org}/code-security/configurations/{configuration_id}/defaults', 'Set a code security configuration as a default for an organization', 'code-security'),
    ('GET', '/orgs/{org}/code-security/configurations/{configuration_id}/repositories', 'Get repositories associated with a code security configuration', 'code-security'),
    ('GET', '/orgs/{org}/codespaces', 'List codespaces for the organization', 'codespaces'),
    ('PUT', '/orgs/{org}/codespaces/access', 'Manage access control for organization codespaces', 'codespaces'),
    ('POST', '/orgs/{org}/codespaces/access/selected_users', 'Add users to Codespaces access for an organization', 'codespaces'),
    ('DELETE', '/orgs/{org}/codespaces/access/selected_users', 'Remove users from Codespaces access for an organization', 'codespaces'),
    ('GET', '/orgs/{org}/codespaces/secrets', 'List organization secrets', 'codespaces'),
    ('GET', '/orgs/{org}/codespaces/secrets/public-key', 'Get an organization public key', 'codespaces'),
    ('GET', '/orgs/{org}/codespaces/secrets/{secret_name}', 'Get an organization secret', 'codespaces'),
    ('PUT', '/orgs/{org}/codespaces/secrets/{secret_name}', 'Create or update an organization secret', 'codespaces'),
    ('DELETE', '/orgs/{org}/codespaces/secrets/{secret_name}', 'Delete an organization secret', 'codespaces'),
    ('GET', '/orgs/{org}/codespaces/secrets/{secret_name}/repositories', 'List selected repositories for an organization secret', 'codespaces'),
    ('PUT', '/orgs/{org}/codespaces/secrets/{secret_name}/repositories', 'Set selected repositories for an organization secret', 'codespaces'),
    ('PUT', '/orgs/{org}/codespaces/secrets/{secret_name}/repositories/{repository_id}', 'Add selected repository to an organization secret', 'codespaces'),
    ('DELETE', '/orgs/{org}/codespaces/secrets/{secret_name}/repositories/{repository_id}', 'Remove selected repository from an organization secret', 'codespaces'),
    ('GET', '/orgs/{org}/copilot-spaces', 'List organization Copilot Spaces', 'copilot-spaces'),
    ('POST', '/orgs/{org}/copilot-spaces', 'Create an organization Copilot Space', 'copilot-spaces'),
    ('GET', '/orgs/{org}/copilot-spaces/{space_number}', 'Get an organization Copilot Space', 'copilot-spaces'),
    ('PUT', '/orgs/{org}/copilot-spaces/{space_number}', 'Set an organization Copilot Space', 'copilot-spaces'),
    ('DELETE', '/orgs/{org}/copilot-spaces/{space_number}', 'Delete an organization Copilot Space', 'copilot-spaces'),
    ('GET', '/orgs/{org}/copilot-spaces/{space_number}/collaborators', 'List collaborators for an organization Copilot Space', 'copilot-spaces'),
    ('POST', '/orgs/{org}/copilot-spaces/{space_number}/collaborators', 'Add a collaborator to an organization Copilot Space', 'copilot-spaces'),
    ('PUT', '/orgs/{org}/copilot-spaces/{space_number}/collaborators/{actor_type}/{actor_identifier}', 'Set a collaborator role for an organization Copilot Space', 'copilot-spaces'),
    ('DELETE', '/orgs/{org}/copilot-spaces/{space_number}/collaborators/{actor_type}/{actor_identifier}', 'Remove a collaborator from an organization Copilot Space', 'copilot-spaces'),
    ('GET', '/orgs/{org}/copilot-spaces/{space_number}/resources', 'List resources for an organization Copilot Space', 'copilot-spaces'),
    ('POST', '/orgs/{org}/copilot-spaces/{space_number}/resources', 'Create a resource for an organization Copilot Space', 'copilot-spaces'),
    ('GET', '/orgs/{org}/copilot-spaces/{space_number}/resources/{space_resource_id}', 'Get a resource for an organization Copilot Space', 'copilot-spaces'),
    ('PUT', '/orgs/{org}/copilot-spaces/{space_number}/resources/{space_resource_id}', 'Set a resource for an organization Copilot Space', 'copilot-spaces'),
    ('DELETE', '/orgs/{org}/copilot-spaces/{space_number}/resources/{space_resource_id}', 'Delete a resource from an organization Copilot Space', 'copilot-spaces'),
    ('GET', '/orgs/{org}/copilot/billing', 'Get Copilot seat information and settings for an organization', 'copilot'),
    ('GET', '/orgs/{org}/copilot/billing/seats', 'List all Copilot seat assignments for an organization', 'copilot'),
    ('POST', '/orgs/{org}/copilot/billing/selected_teams', 'Add teams to the Copilot subscription for an organization', 'copilot'),
    ('DELETE', '/orgs/{org}/copilot/billing/selected_teams', 'Remove teams from the Copilot subscription for an organization', 'copilot'),
    ('POST', '/orgs/{org}/copilot/billing/selected_users', 'Add users to the Copilot subscription for an organization', 'copilot'),
    ('DELETE', '/orgs/{org}/copilot/billing/selected_users', 'Remove users from the Copilot subscription for an organization', 'copilot'),
    ('GET', '/orgs/{org}/copilot/coding-agent/permissions', 'Get Copilot cloud agent permissions for an organization', 'copilot'),
    ('PUT', '/orgs/{org}/copilot/coding-agent/permissions', 'Set Copilot cloud agent permissions for an organization', 'copilot'),
    ('GET', '/orgs/{org}/copilot/coding-agent/permissions/repositories', 'List repositories enabled for Copilot cloud agent in an organization', 'copilot'),
    ('PUT', '/orgs/{org}/copilot/coding-agent/permissions/repositories', 'Set selected repositories for Copilot cloud agent in an organization', 'copilot'),
    ('PUT', '/orgs/{org}/copilot/coding-agent/permissions/repositories/{repository_id}', 'Enable a repository for Copilot cloud agent in an organization', 'copilot'),
    ('DELETE', '/orgs/{org}/copilot/coding-agent/permissions/repositories/{repository_id}', 'Disable a repository for Copilot cloud agent in an organization', 'copilot'),
    ('GET', '/orgs/{org}/copilot/content_exclusion', 'Get Copilot content exclusion rules for an organization', 'copilot'),
    ('PUT', '/orgs/{org}/copilot/content_exclusion', 'Set Copilot content exclusion rules for an organization', 'copilot'),
    ('GET', '/orgs/{org}/copilot/metrics/reports/organization-1-day', 'Get Copilot organization usage metrics for a specific day', 'copilot'),
    ('GET', '/orgs/{org}/copilot/metrics/reports/organization-28-day/latest', 'Get Copilot organization usage metrics', 'copilot'),
    ('GET', '/orgs/{org}/copilot/metrics/reports/user-teams-1-day', 'Get Copilot organization user-teams report for a specific day', 'copilot'),
    ('GET', '/orgs/{org}/copilot/metrics/reports/users-1-day', 'Get Copilot organization users usage metrics for a specific day', 'copilot'),
    ('GET', '/orgs/{org}/copilot/metrics/reports/users-28-day/latest', 'Get Copilot organization users usage metrics', 'copilot'),
    ('GET', '/orgs/{org}/dependabot/alerts', 'List Dependabot alerts for an organization', 'dependabot'),
    ('GET', '/orgs/{org}/dependabot/repository-access', 'Lists the repositories Dependabot can access in an organization', 'dependabot'),
    ('PATCH', '/orgs/{org}/dependabot/repository-access', "Updates Dependabot's repository access list for an organization", 'dependabot'),
    ('PUT', '/orgs/{org}/dependabot/repository-access/default-level', 'Set the default repository access level for Dependabot', 'dependabot'),
    ('GET', '/orgs/{org}/dependabot/secrets', 'List organization secrets', 'dependabot'),
    ('GET', '/orgs/{org}/dependabot/secrets/public-key', 'Get an organization public key', 'dependabot'),
    ('GET', '/orgs/{org}/dependabot/secrets/{secret_name}', 'Get an organization secret', 'dependabot'),
    ('PUT', '/orgs/{org}/dependabot/secrets/{secret_name}', 'Create or update an organization secret', 'dependabot'),
    ('DELETE', '/orgs/{org}/dependabot/secrets/{secret_name}', 'Delete an organization secret', 'dependabot'),
    ('GET', '/orgs/{org}/dependabot/secrets/{secret_name}/repositories', 'List selected repositories for an organization secret', 'dependabot'),
    ('PUT', '/orgs/{org}/dependabot/secrets/{secret_name}/repositories', 'Set selected repositories for an organization secret', 'dependabot'),
    ('PUT', '/orgs/{org}/dependabot/secrets/{secret_name}/repositories/{repository_id}', 'Add selected repository to an organization secret', 'dependabot'),
    ('DELETE', '/orgs/{org}/dependabot/secrets/{secret_name}/repositories/{repository_id}', 'Remove selected repository from an organization secret', 'dependabot'),
    ('GET', '/orgs/{org}/docker/conflicts', 'Get list of conflicting packages during Docker migration for organization', 'packages'),
    ('GET', '/orgs/{org}/events', 'List public organization events', 'activity'),
    ('GET', '/orgs/{org}/failed_invitations', 'List failed organization invitations', 'orgs'),
    ('GET', '/orgs/{org}/hooks', 'List organization webhooks', 'orgs'),
    ('POST', '/orgs/{org}/hooks', 'Create an organization webhook', 'orgs'),
    ('GET', '/orgs/{org}/hooks/{hook_id}', 'Get an organization webhook', 'orgs'),
    ('PATCH', '/orgs/{org}/hooks/{hook_id}', 'Update an organization webhook', 'orgs'),
    ('DELETE', '/orgs/{org}/hooks/{hook_id}', 'Delete an organization webhook', 'orgs'),
    ('GET', '/orgs/{org}/hooks/{hook_id}/config', 'Get a webhook configuration for an organization', 'orgs'),
    ('PATCH', '/orgs/{org}/hooks/{hook_id}/config', 'Update a webhook configuration for an organization', 'orgs'),
    ('GET', '/orgs/{org}/hooks/{hook_id}/deliveries', 'List deliveries for an organization webhook', 'orgs'),
    ('GET', '/orgs/{org}/hooks/{hook_id}/deliveries/{delivery_id}', 'Get a webhook delivery for an organization webhook', 'orgs'),
    ('POST', '/orgs/{org}/hooks/{hook_id}/deliveries/{delivery_id}/attempts', 'Redeliver a delivery for an organization webhook', 'orgs'),
    ('POST', '/orgs/{org}/hooks/{hook_id}/pings', 'Ping an organization webhook', 'orgs'),
    ('GET', '/orgs/{org}/insights/api/route-stats/{actor_type}/{actor_id}', 'Get route stats by actor', 'orgs'),
    ('GET', '/orgs/{org}/insights/api/subject-stats', 'Get subject stats', 'orgs'),
    ('GET', '/orgs/{org}/insights/api/summary-stats', 'Get summary stats', 'orgs'),
    ('GET', '/orgs/{org}/insights/api/summary-stats/users/{user_id}', 'Get summary stats by user', 'orgs'),
    ('GET', '/orgs/{org}/insights/api/summary-stats/{actor_type}/{actor_id}', 'Get summary stats by actor', 'orgs'),
    ('GET', '/orgs/{org}/insights/api/time-stats', 'Get time stats', 'orgs'),
    ('GET', '/orgs/{org}/insights/api/time-stats/users/{user_id}', 'Get time stats by user', 'orgs'),
    ('GET', '/orgs/{org}/insights/api/time-stats/{actor_type}/{actor_id}', 'Get time stats by actor', 'orgs'),
    ('GET', '/orgs/{org}/insights/api/user-stats/{user_id}', 'Get user stats', 'orgs'),
    ('GET', '/orgs/{org}/installation', 'Get an organization installation for the authenticated app', 'apps'),
    ('GET', '/orgs/{org}/installations', 'List app installations for an organization', 'orgs'),
    ('GET', '/orgs/{org}/interaction-limits', 'Get interaction restrictions for an organization', 'interactions'),
    ('PUT', '/orgs/{org}/interaction-limits', 'Set interaction restrictions for an organization', 'interactions'),
    ('DELETE', '/orgs/{org}/interaction-limits', 'Remove interaction restrictions for an organization', 'interactions'),
    ('GET', '/orgs/{org}/invitations', 'List pending organization invitations', 'orgs'),
    ('POST', '/orgs/{org}/invitations', 'Create an organization invitation', 'orgs'),
    ('DELETE', '/orgs/{org}/invitations/{invitation_id}', 'Cancel an organization invitation', 'orgs'),
    ('GET', '/orgs/{org}/invitations/{invitation_id}/teams', 'List organization invitation teams', 'orgs'),
    ('GET', '/orgs/{org}/issue-fields', 'List issue fields for an organization', 'orgs'),
    ('POST', '/orgs/{org}/issue-fields', 'Create issue field for an organization', 'orgs'),
    ('PATCH', '/orgs/{org}/issue-fields/{issue_field_id}', 'Update issue field for an organization', 'orgs'),
    ('DELETE', '/orgs/{org}/issue-fields/{issue_field_id}', 'Delete issue field for an organization', 'orgs'),
    ('GET', '/orgs/{org}/issue-types', 'List issue types for an organization', 'orgs'),
    ('POST', '/orgs/{org}/issue-types', 'Create issue type for an organization', 'orgs'),
    ('PUT', '/orgs/{org}/issue-types/{issue_type_id}', 'Update issue type for an organization', 'orgs'),
    ('DELETE', '/orgs/{org}/issue-types/{issue_type_id}', 'Delete issue type for an organization', 'orgs'),
    ('GET', '/orgs/{org}/issues', 'List organization issues assigned to the authenticated user', 'issues'),
    ('GET', '/orgs/{org}/members', 'List organization members', 'orgs'),
    ('GET', '/orgs/{org}/members/{username}', 'Check organization membership for a user', 'orgs'),
    ('DELETE', '/orgs/{org}/members/{username}', 'Remove an organization member', 'orgs'),
    ('GET', '/orgs/{org}/members/{username}/codespaces', 'List codespaces for a user in organization', 'codespaces'),
    ('DELETE', '/orgs/{org}/members/{username}/codespaces/{codespace_name}', 'Delete a codespace from the organization', 'codespaces'),
    ('POST', '/orgs/{org}/members/{username}/codespaces/{codespace_name}/stop', 'Stop a codespace for an organization user', 'codespaces'),
    ('GET', '/orgs/{org}/members/{username}/copilot', 'Get Copilot seat assignment details for a user', 'copilot'),
    ('GET', '/orgs/{org}/memberships/{username}', 'Get organization membership for a user', 'orgs'),
    ('PUT', '/orgs/{org}/memberships/{username}', 'Set organization membership for a user', 'orgs'),
    ('DELETE', '/orgs/{org}/memberships/{username}', 'Remove organization membership for a user', 'orgs'),
    ('GET', '/orgs/{org}/migrations', 'List organization migrations', 'migrations'),
    ('POST', '/orgs/{org}/migrations', 'Start an organization migration', 'migrations'),
    ('GET', '/orgs/{org}/migrations/{migration_id}', 'Get an organization migration status', 'migrations'),
    ('GET', '/orgs/{org}/migrations/{migration_id}/archive', 'Download an organization migration archive', 'migrations'),
    ('DELETE', '/orgs/{org}/migrations/{migration_id}/archive', 'Delete an organization migration archive', 'migrations'),
    ('DELETE', '/orgs/{org}/migrations/{migration_id}/repos/{repo_name}/lock', 'Unlock an organization repository', 'migrations'),
    ('GET', '/orgs/{org}/migrations/{migration_id}/repositories', 'List repositories in an organization migration', 'migrations'),
    ('GET', '/orgs/{org}/organization-roles', 'Get all organization roles for an organization', 'orgs'),
    ('DELETE', '/orgs/{org}/organization-roles/teams/{team_slug}', 'Remove all organization roles for a team', 'orgs'),
    ('PUT', '/orgs/{org}/organization-roles/teams/{team_slug}/{role_id}', 'Assign an organization role to a team', 'orgs'),
    ('DELETE', '/orgs/{org}/organization-roles/teams/{team_slug}/{role_id}', 'Remove an organization role from a team', 'orgs'),
    ('DELETE', '/orgs/{org}/organization-roles/users/{username}', 'Remove all organization roles for a user', 'orgs'),
    ('PUT', '/orgs/{org}/organization-roles/users/{username}/{role_id}', 'Assign an organization role to a user', 'orgs'),
    ('DELETE', '/orgs/{org}/organization-roles/users/{username}/{role_id}', 'Remove an organization role from a user', 'orgs'),
    ('GET', '/orgs/{org}/organization-roles/{role_id}', 'Get an organization role', 'orgs'),
    ('GET', '/orgs/{org}/organization-roles/{role_id}/teams', 'List teams that are assigned to an organization role', 'orgs'),
    ('GET', '/orgs/{org}/organization-roles/{role_id}/users', 'List users that are assigned to an organization role', 'orgs'),
    ('GET', '/orgs/{org}/outside_collaborators', 'List outside collaborators for an organization', 'orgs'),
    ('PUT', '/orgs/{org}/outside_collaborators/{username}', 'Convert an organization member to outside collaborator', 'orgs'),
    ('DELETE', '/orgs/{org}/outside_collaborators/{username}', 'Remove outside collaborator from an organization', 'orgs'),
    ('GET', '/orgs/{org}/packages', 'List packages for an organization', 'packages'),
    ('GET', '/orgs/{org}/packages/{package_type}/{package_name}', 'Get a package for an organization', 'packages'),
    ('DELETE', '/orgs/{org}/packages/{package_type}/{package_name}', 'Delete a package for an organization', 'packages'),
    ('POST', '/orgs/{org}/packages/{package_type}/{package_name}/restore', 'Restore a package for an organization', 'packages'),
    ('GET', '/orgs/{org}/packages/{package_type}/{package_name}/versions', 'List package versions for a package owned by an organization', 'packages'),
    ('GET', '/orgs/{org}/packages/{package_type}/{package_name}/versions/{package_version_id}', 'Get a package version for an organization', 'packages'),
    ('DELETE', '/orgs/{org}/packages/{package_type}/{package_name}/versions/{package_version_id}', 'Delete package version for an organization', 'packages'),
    ('POST', '/orgs/{org}/packages/{package_type}/{package_name}/versions/{package_version_id}/restore', 'Restore package version for an organization', 'packages'),
    ('GET', '/orgs/{org}/personal-access-token-requests', 'List requests to access organization resources with fine-grained personal access tokens', 'orgs'),
    ('POST', '/orgs/{org}/personal-access-token-requests', 'Review requests to access organization resources with fine-grained personal access tokens', 'orgs'),
    ('POST', '/orgs/{org}/personal-access-token-requests/{pat_request_id}', 'Review a request to access organization resources with a fine-grained personal access token', 'orgs'),
    ('GET', '/orgs/{org}/personal-access-token-requests/{pat_request_id}/repositories', 'List repositories requested to be accessed by a fine-grained personal access token', 'orgs'),
    ('GET', '/orgs/{org}/personal-access-tokens', 'List fine-grained personal access tokens with access to organization resources', 'orgs'),
    ('POST', '/orgs/{org}/personal-access-tokens', 'Update the access to organization resources via fine-grained personal access tokens', 'orgs'),
    ('POST', '/orgs/{org}/personal-access-tokens/{pat_id}', 'Update the access a fine-grained personal access token has to organization resources', 'orgs'),
    ('GET', '/orgs/{org}/personal-access-tokens/{pat_id}/repositories', 'List repositories a fine-grained personal access token has access to', 'orgs'),
    ('GET', '/orgs/{org}/private-registries', 'List private registries for an organization', 'private-registries'),
    ('POST', '/orgs/{org}/private-registries', 'Create a private registry for an organization', 'private-registries'),
    ('GET', '/orgs/{org}/private-registries/public-key', 'Get private registries public key for an organization', 'private-registries'),
    ('GET', '/orgs/{org}/private-registries/{secret_name}', 'Get a private registry for an organization', 'private-registries'),
    ('PATCH', '/orgs/{org}/private-registries/{secret_name}', 'Update a private registry for an organization', 'private-registries'),
    ('DELETE', '/orgs/{org}/private-registries/{secret_name}', 'Delete a private registry for an organization', 'private-registries'),
    ('GET', '/orgs/{org}/projectsV2', 'List projects for organization', 'projects'),
    ('GET', '/orgs/{org}/projectsV2/{project_number}', 'Get project for organization', 'projects'),
    ('POST', '/orgs/{org}/projectsV2/{project_number}/drafts', 'Create draft item for organization owned project', 'projects'),
    ('GET', '/orgs/{org}/projectsV2/{project_number}/fields', 'List project fields for organization', 'projects'),
    ('POST', '/orgs/{org}/projectsV2/{project_number}/fields', 'Add a field to an organization-owned project.', 'projects'),
    ('GET', '/orgs/{org}/projectsV2/{project_number}/fields/{field_id}', 'Get project field for organization', 'projects'),
    ('GET', '/orgs/{org}/projectsV2/{project_number}/items', 'List items for an organization owned project', 'projects'),
    ('POST', '/orgs/{org}/projectsV2/{project_number}/items', 'Add item to organization owned project', 'projects'),
    ('GET', '/orgs/{org}/projectsV2/{project_number}/items/{item_id}', 'Get an item for an organization owned project', 'projects'),
    ('PATCH', '/orgs/{org}/projectsV2/{project_number}/items/{item_id}', 'Update project item for organization', 'projects'),
    ('DELETE', '/orgs/{org}/projectsV2/{project_number}/items/{item_id}', 'Delete project item for organization', 'projects'),
    ('POST', '/orgs/{org}/projectsV2/{project_number}/views', 'Create a view for an organization-owned project', 'projects'),
    ('GET', '/orgs/{org}/projectsV2/{project_number}/views/{view_number}/items', 'List items for an organization project view', 'projects'),
    ('GET', '/orgs/{org}/properties/schema', 'Get all custom properties for an organization', 'orgs'),
    ('PATCH', '/orgs/{org}/properties/schema', 'Create or update custom properties for an organization', 'orgs'),
    ('GET', '/orgs/{org}/properties/schema/{custom_property_name}', 'Get a custom property for an organization', 'orgs'),
    ('PUT', '/orgs/{org}/properties/schema/{custom_property_name}', 'Create or update a custom property for an organization', 'orgs'),
    ('DELETE', '/orgs/{org}/properties/schema/{custom_property_name}', 'Remove a custom property for an organization', 'orgs'),
    ('GET', '/orgs/{org}/properties/values', 'List custom property values for organization repositories', 'orgs'),
    ('PATCH', '/orgs/{org}/properties/values', 'Create or update custom property values for organization repositories', 'orgs'),
    ('GET', '/orgs/{org}/public_members', 'List public organization members', 'orgs'),
    ('GET', '/orgs/{org}/public_members/{username}', 'Check public organization membership for a user', 'orgs'),
    ('PUT', '/orgs/{org}/public_members/{username}', 'Set public organization membership for the authenticated user', 'orgs'),
    ('DELETE', '/orgs/{org}/public_members/{username}', 'Remove public organization membership for the authenticated user', 'orgs'),
    ('GET', '/orgs/{org}/repos', 'List organization repositories', 'repos'),
    ('POST', '/orgs/{org}/repos', 'Create an organization repository', 'repos'),
    ('GET', '/orgs/{org}/rulesets', 'Get all organization repository rulesets', 'orgs'),
    ('POST', '/orgs/{org}/rulesets', 'Create an organization repository ruleset', 'orgs'),
    ('GET', '/orgs/{org}/rulesets/rule-suites', 'List organization rule suites', 'orgs'),
    ('GET', '/orgs/{org}/rulesets/rule-suites/{rule_suite_id}', 'Get an organization rule suite', 'orgs'),
    ('GET', '/orgs/{org}/rulesets/{ruleset_id}', 'Get an organization repository ruleset', 'orgs'),
    ('PUT', '/orgs/{org}/rulesets/{ruleset_id}', 'Update an organization repository ruleset', 'orgs'),
    ('DELETE', '/orgs/{org}/rulesets/{ruleset_id}', 'Delete an organization repository ruleset', 'orgs'),
    ('GET', '/orgs/{org}/rulesets/{ruleset_id}/history', 'Get organization ruleset history', 'orgs'),
    ('GET', '/orgs/{org}/rulesets/{ruleset_id}/history/{version_id}', 'Get organization ruleset version', 'orgs'),
    ('GET', '/orgs/{org}/secret-scanning/alerts', 'List secret scanning alerts for an organization', 'secret-scanning'),
    ('GET', '/orgs/{org}/secret-scanning/pattern-configurations', 'List organization pattern configurations', 'secret-scanning'),
    ('PATCH', '/orgs/{org}/secret-scanning/pattern-configurations', 'Update organization pattern configurations', 'secret-scanning'),
    ('GET', '/orgs/{org}/security-advisories', 'List repository security advisories for an organization', 'security-advisories'),
    ('GET', '/orgs/{org}/security-managers', 'List security manager teams', 'orgs'),
    ('PUT', '/orgs/{org}/security-managers/teams/{team_slug}', 'Add a security manager team', 'orgs'),
    ('DELETE', '/orgs/{org}/security-managers/teams/{team_slug}', 'Remove a security manager team', 'orgs'),
    ('GET', '/orgs/{org}/settings/immutable-releases', 'Get immutable releases settings for an organization', 'orgs'),
    ('PUT', '/orgs/{org}/settings/immutable-releases', 'Set immutable releases settings for an organization', 'orgs'),
    ('GET', '/orgs/{org}/settings/immutable-releases/repositories', 'List selected repositories for immutable releases enforcement', 'orgs'),
    ('PUT', '/orgs/{org}/settings/immutable-releases/repositories', 'Set selected repositories for immutable releases enforcement', 'orgs'),
    ('PUT', '/orgs/{org}/settings/immutable-releases/repositories/{repository_id}', 'Enable a selected repository for immutable releases in an organization', 'orgs'),
    ('DELETE', '/orgs/{org}/settings/immutable-releases/repositories/{repository_id}', 'Disable a selected repository for immutable releases in an organization', 'orgs'),
    ('GET', '/orgs/{org}/settings/network-configurations', 'List hosted compute network configurations for an organization', 'orgs'),
    ('POST', '/orgs/{org}/settings/network-configurations', 'Create a hosted compute network configuration for an organization', 'orgs'),
    ('GET', '/orgs/{org}/settings/network-configurations/{network_configuration_id}', 'Get a hosted compute network configuration for an organization', 'orgs'),
    ('PATCH', '/orgs/{org}/settings/network-configurations/{network_configuration_id}', 'Update a hosted compute network configuration for an organization', 'orgs'),
    ('DELETE', '/orgs/{org}/settings/network-configurations/{network_configuration_id}', 'Delete a hosted compute network configuration from an organization', 'orgs'),
    ('GET', '/orgs/{org}/settings/network-settings/{network_settings_id}', 'Get a hosted compute network settings resource for an organization', 'orgs'),
    ('GET', '/orgs/{org}/teams', 'List teams', 'teams'),
    ('POST', '/orgs/{org}/teams', 'Create a team', 'teams'),
    ('GET', '/orgs/{org}/teams/{team_slug}', 'Get a team by name', 'teams'),
    ('PATCH', '/orgs/{org}/teams/{team_slug}', 'Update a team', 'teams'),
    ('DELETE', '/orgs/{org}/teams/{team_slug}', 'Delete a team', 'teams'),
    ('GET', '/orgs/{org}/teams/{team_slug}/invitations', 'List pending team invitations', 'teams'),
    ('GET', '/orgs/{org}/teams/{team_slug}/members', 'List team members', 'teams'),
    ('GET', '/orgs/{org}/teams/{team_slug}/memberships/{username}', 'Get team membership for a user', 'teams'),
    ('PUT', '/orgs/{org}/teams/{team_slug}/memberships/{username}', 'Add or update team membership for a user', 'teams'),
    ('DELETE', '/orgs/{org}/teams/{team_slug}/memberships/{username}', 'Remove team membership for a user', 'teams'),
    ('GET', '/orgs/{org}/teams/{team_slug}/repos', 'List team repositories', 'teams'),
    ('GET', '/orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}', 'Check team permissions for a repository', 'teams'),
    ('PUT', '/orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}', 'Add or update team repository permissions', 'teams'),
    ('DELETE', '/orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}', 'Remove a repository from a team', 'teams'),
    ('GET', '/orgs/{org}/teams/{team_slug}/teams', 'List child teams', 'teams'),
    ('POST', '/orgs/{org}/{security_product}/{enablement}', 'Enable or disable a security feature for an organization', 'orgs'),
    ('GET', '/rate_limit', 'Get rate limit status for the authenticated user', 'rate-limit'),
    ('GET', '/user', 'Get the authenticated user', 'users'),
    ('PATCH', '/user', 'Update the authenticated user', 'users'),
    ('GET', '/user/memberships/orgs/{org}', 'Get an organization membership for the authenticated user', 'orgs'),
    ('PATCH', '/user/memberships/orgs/{org}', 'Update an organization membership for the authenticated user', 'orgs'),
    ('GET', '/users/{username}/events/orgs/{org}', 'List organization events for the authenticated user', 'activity'),
]
